cmake: fix building with dynamic linking
Summary:
...by forcing conv_analysis to be built as a static library. Fixes this
build error when building with -DBUILD_SHARED_LIBS=ON:

  $ ninja
  [...]
  FAILED: tools/single_conv_layer
  : && /nix/store/d73n3asch2cw3ylqi0y6jqqqa9qfk6fc-gcc-wrapper-10.3.0/bin/g++ -Wall -Werror -pedantic -pedantic-errors -Wvla -Wno-maybe-uninitialized -Wno-error=deprecated-declarations  tools/CMakeFiles/single_conv_layer.dir/single_conv_layer.cpp.o -o tools/single_conv_layer  -Wl,-rpath,/localdata/bjornf/poplarview/poplibs/build/lib/poprand:/localdata/bjornf/poplarview/poplibs/build/lib/popnn:/localdata/bjornf/poplarview/poplibs/build/lib/popfloat:/localdata/bjornf/poplarview/poplibs/build/lib/popsparse:/localdata/bjornf/poplarview/poplibs/build/tools:/localdata/bjornf/poplarview/poplibs/build/lib/poplibs_test:/localdata/bjornf/poplarview/poplibs/build/lib/poplin:/localdata/bjornf/poplarview/poplibs/build/lib/popops:/localdata/bjornf/poplarview/poplibs/build/lib/poputil:  lib/poprand/libpoprand.so  lib/popnn/libpopnn.so  lib/popfloat/libpopfloat.so  /nix/store/isinh885qwc8zip8ivwcwa1agizjkdb3-graphcore-boost/lib/libboost_filesystem.so.1.70.0  lib/popsparse/libpopsparse.so  tools/libconv_analysis.so  lib/poplibs_support/libpoplibs_support.a  lib/poplibs_test/libpoplibs_test.so  /nix/store/isinh885qwc8zip8ivwcwa1agizjkdb3-graphcore-boost/lib/libboost_program_options.so.1.70.0  lib/poplin/libpoplin.so  lib/popops/libpopops.so  /nix/store/6jlxxrs2qx78i32w69rcwjbhw1qbpg02-graphcore-zoltan/lib/libzoltan.a  /nix/store/6jlxxrs2qx78i32w69rcwjbhw1qbpg02-graphcore-zoltan/lib/libsimpi.a  lib/poputil/libpoputil.so  /nix/store/jj6kw2vyn2fvfn6d2m2vqixjg7ccp9i0-graphcore-poplar/lib64/libpoplar_test.so  /nix/store/jj6kw2vyn2fvfn6d2m2vqixjg7ccp9i0-graphcore-poplar/lib64/libpoplar.so  /nix/store/i3r8b3ciwhlkna1pmislmdlgp97lkhhq-graphcore-libpvti/lib64/libpvti.so  /nix/store/qddbs4i4ji7rram9j02whkz6nrnawf7z-graphcore-libpva/lib64/libpva.so  -ldl  -lpthread && :
  /nix/store/2cl8h183p6xsnq2vbqv2jlwg4mp1bhgg-binutils-2.35.2/bin/ld: tools/CMakeFiles/single_conv_layer.dir/single_conv_layer.cpp.o: in function `main':
  single_conv_layer.cpp:(.text.startup+0x4b25): undefined reference to `amp::updateDetailedPlanCosts(bool, bool, poplin::internal::DetailedPlanCosts&)'
  /nix/store/2cl8h183p6xsnq2vbqv2jlwg4mp1bhgg-binutils-2.35.2/bin/ld: single_conv_layer.cpp:(.text.startup+0x4b6d): undefined reference to `amp::getMeasuredCosts(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long, bool, bool, bool)'
  /nix/store/2cl8h183p6xsnq2vbqv2jlwg4mp1bhgg-binutils-2.35.2/bin/ld: single_conv_layer.cpp:(.text.startup+0x4b94): undefined reference to `amp::compareCosts(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, poplin::internal::DetailedPlanCosts const&, amp::MeasuredPlanCosts const&, bool, bool, bool)'
  /nix/store/2cl8h183p6xsnq2vbqv2jlwg4mp1bhgg-binutils-2.35.2/bin/ld: single_conv_layer.cpp:(.text.startup+0x5011): undefined reference to `amp::getSimulatedCosts(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, bool, bool, bool)'
  /nix/store/2cl8h183p6xsnq2vbqv2jlwg4mp1bhgg-binutils-2.35.2/bin/ld: single_conv_layer.cpp:(.text.startup+0x5dfc): undefined reference to `amp::updateDetailedPlanCosts(bool, bool, poplin::internal::DetailedPlanCosts&)'
  /nix/store/2cl8h183p6xsnq2vbqv2jlwg4mp1bhgg-binutils-2.35.2/bin/ld: single_conv_layer.cpp:(.text.startup+0x9169): undefined reference to `amp::getMeasuredCosts(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long, bool, bool, bool)'
  /nix/store/2cl8h183p6xsnq2vbqv2jlwg4mp1bhgg-binutils-2.35.2/bin/ld: single_conv_layer.cpp:(.text.startup+0x9191): undefined reference to `amp::compareCosts(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, poplin::internal::DetailedPlanCosts const&, amp::MeasuredPlanCosts const&, bool, bool, bool)'
  /nix/store/2cl8h183p6xsnq2vbqv2jlwg4mp1bhgg-binutils-2.35.2/bin/ld: single_conv_layer.cpp:(.text.startup+0x9240): undefined reference to `amp::getSimulatedCosts(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, bool, bool, bool)'
  collect2: error: ld returned 1 exit status
  ninja: build stopped: subcommand failed.

Fixes: df1d490deb ("Automate analysis of simulator trace timing")

Ref T38785.
Fixes T67933.

Reviewers: #poplar_team, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, mattl

Reviewed By: #poplar_team, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, mattl

Subscribers: mattl

Maniphest Tasks: T38785, T67933

Differential Revision: https://phabricator.sourcevertex.net/D73633