Fix compile errors with clang 8
Summary:
Fix issues causing:
* ConvModel.cpp:1508:25: error: lambda capture 'defaultBytesPerCycle' is not used [-Werror,-Wunused-lambda-capture]

Ref T34131.

Reviewers: #poplar_team, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, jorgec

Reviewed By: #poplar_team, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, jorgec

Maniphest Tasks: T34131

Differential Revision: https://phabricator.sourcevertex.net/D43850