Fix compile errors with clang 8
Summary:
Fix issues causing:

* build-8/install/boost/include/boost/lexical_cast/detail/converter_lexical.hpp:243:13: error: static_assert failed due to requirement 'has_right_shift<std::basic_istream<char>, popops::SortOrder, boost::binary_op_detail::dont_care>::value || boost::has_right_shift<std::basic_istream<wchar_t>, popops::SortOrder, boost::binary_op_detail::dont_care>::value' "Target type is neither std::istream`able nor std::wistream`able"
* include/popnn/Gru.hpp:54:3: error: explicitly defaulted default constructor is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
* include/popnn/Lstm.hpp:57:3: error: explicitly defaulted default constructor is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
* lib/popnn/PerformanceEstimation.hpp:313:49: error: operator '?:' has lower precedence than '+'; '+' will be evaluated first [-Werror,-Wparentheses]
* lib/popnn/PerformanceEstimation.hpp:329:54: error: operator '?:' has lower precedence than '+'; '+' will be evaluated first [-Werror,-Wparentheses]
* lib/popnn/CTCLossPlan.cpp:548:9: error: lambda capture 'params' is not used [-Werror,-Wunused-lambda-capture]
* lib/popnn/Lstm.cpp:1349:50: error: lambda capture 'numShards' is not used [-Werror,-Wunused-lambda-capture]
* lib/popnn/Rnn.cpp:756:25: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]

Ref T34131.

Reviewers: #poplar_team, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, saml

Reviewed By: #poplar_team, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, saml

Subscribers: saml

Maniphest Tasks: T34131

Differential Revision: https://phabricator.sourcevertex.net/D41793