Fix compile errors with clang 8
Summary:
Fix issues causing:

* BinaryCodeletsTest.cpp:517:18: error: variable 'val2' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]

Ref T34131.

Reviewers: #poplar_team, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, mattl

Reviewed By: #poplar_team, #framework_ip_review_-_any_oss_or_third-party_code_use_has_been_approved, mattl

Maniphest Tasks: T34131

Differential Revision: https://phabricator.sourcevertex.net/D43354